---
- hosts: all
  tasks:
- sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    sysctl_set: yes
    state: present
    reload: yes	
- sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: 1
    sysctl_set: yes
    state: present
    reload: yes	
- sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: 1
    sysctl_set: yes
    state: present
    reload: yes	
- sysctl:
    name: fs.file-max
    value: 65536
    sysctl_set: yes
    state: present
    reload: yes	
- sysctl:
    name: vm.max_map_count
    value: 262144
    sysctl_set: yes
    state: present
    reload: yes
